### ISSUE TITLE
What about CSS?

### ISSUE THREAD

**Issue by rubencodes** [yogaboll/react-npm-component-starter#1]
Hi,

Thanks for the component starter kit! I'm curious how one would go about including CSS in their component. Right now this seems to handle CSS properly for the docs website, but in the /lib folder, styles are neither bundled together nor handled in any specific way, leading to `require("*.css")` statements pointing to nowhere.

How could one go about handling this, maybe compiling the css into an index.css file that could be imported by the user? Thanks!

**Comment by markusenglund** [comment]
Hey,

You're correct, I didn't include a way to handle css. My recommendation would be to create a css file in the src/lib folder. It will then be automatically copied to the generated lib folder if you add `--copy-files` at the end of the lib scripts in package.json like this:
```
    "lib": "babel src/lib -d lib --copy-files",
    "lib:watch": "babel src/lib -w -d lib --copy-files",
```

Then import the generated css file copy (I named it styles.css) in src/docs/index.jsx like so:
`import "../lib/styles.css";`

I created a branch called "component-style" on this repository that shows this setup.

Then you have to tell users of your package to import it separately like `import <your-package-name>/lib/styles.css` [like on this repo](https://github.com/JedWatson/react-select#installation).

Another option is to only use inline-styles. Meaning like this: 
`<button style={{background: "blue", width: 20 }} >test</button>`

This is a bit simpler since the user of your package doesn't have to separately import a css file. The downside is that you can't use pseudo-selectors like `:focus` and such which can be a deal breaker.

**Comment by rubencodes** [comment]
Ah, thanks for the help! I'll give it a shot. I tried doing inline-styles, but adding logic to deal with prefixing (specifically value prefixing) was going to be a headache, and adding another package dependency just to help with that seemed overkill.
