### ISSUE TITLE
using this in an ejected CRA project Failed to minify the code Error

### ISSUE THREAD

**Issue by jasan-s** [yogaboll/react-npm-component-starter#10]
i am using this starter to create a npm module. If i import this creating module to an Ejected CRA app and try building i get an error : `Failed to minify the code from this file:`   this is due to the es6 features within my npm module. Any suggestion to how i can transpile `lib` to es5 because CRA does not transpile modules

**Comment by markusenglund** [comment]
Hey,

I don't know why your library was not transpiled to es5. The intended behavior if of course that it should be transpiled.

But anyway, I'm deprecating this boilerplate since I don't have the time to maintain it, and I think other boilerplates are better - like [this one for example](https://github.com/transitive-bullshit/react-modern-library-boilerplate) which I suggest you use instead.
