### ISSUE TITLE
Prop Types Package

### ISSUE THREAD

**Issue by DZuz14** [yogaboll/react-npm-component-starter#4]
This starter kit was extremely helpful. Is there anyway you could add support for the  prop-types package?

**Comment by markusenglund** [comment]
I don't want to include prop-types by default since some developers might not think it's necessary. However, I personally think that it's a good idea to use prop-types in your package. There is nothing in this project that prevents you from using it, so please go ahead and include prop-types in your package!

PS. Install it as a normal dependency, and not a peerDependency. [Source](https://github.com/facebook/prop-types/issues/44)
