### ISSUE TITLE
css discussion

### ISSUE THREAD

**Issue by zfan40** [yogaboll/react-npm-component-starter#5]
I had a hard time dealing with css, like you introduced at the bottom of the doc.
It's definitely a headache and I didn't come up with better solutions. Any possible optimizations here??

**Comment by markusenglund** [comment]
I'm not sure I understand the question. I don't think there is a better solution than the two options I outlined in the README. There is a third option, which is to use a css-in-js library to write the styles but I don't like it since it adds a lot of kilobytes to your library.

I don't know of any more optimizations.
