### ISSUE TITLE
react-app environments are undefined

### ISSUE THREAD

**Issue by kemalyen** [yogaboll/react-npm-component-starter#6]
I've created a simple component for testing purpose. But could not able to load environments.

Here my .env file:

```javascript
REACT_APP_API_KEY="FORBIDDEN"
```

But when I try to access it via following code it's failing.

```javascript
console.log(process.env.REACT_APP_API_KEY)
```

what's going on?

**Comment by markusenglund** [comment]
You need a way to insert the contents of .env into the process.env object. Maybe you can try [this webpack plugin](https://webpack.js.org/plugins/environment-plugin) or [dotenv](https://github.com/motdotla/dotenv).

Keep in mind that you're writing client side code. This means that it is impossible to keep your API key secret, since it will be available in plain text on the users browser in the end. So I don't really see a point in using an env variable instead of a normal variable.

**Comment by kemalyen** [comment]
After many hours later I've given up. But the starter is great and very friendly.
